keystore = "/Users/Jay/tmp"
estimated_gas_cost_of_withdraw = 100000

[home]
account = "0x65529455c1de29136be2f57f1924d619b0145247"
rpc_host = "https://sokol.poa.network"
rpc_port = 443
required_confirmations = 0
password = "/Users/Jay/tmp/password.txt"
contract = { bin = "compiled_contracts/HomeBridge.bin" }

[foreign]
account = "0x65529455c1de29136be2f57f1924d619b0145247"
rpc_host = "https://kovan.infura.io/mew"
rpc_port = 443
required_confirmations = 0
password = "/Users/Jay/tmp/password.txt"
contract = { bin = "compiled_contracts/ForeignBridge.bin" }

[authorities]
accounts = [
    "0x006e27b6a72e1f34c626762f3c4761547aff1421",
    "0x006e27b6a72e1f34c626762f3c4761547aff1421",
    "0x006e27b6a72e1f34c626762f3c4761547aff1421"
]
required_signatures = 2

[transactions]
deposit_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_confirm = { gas = 3000000, gas_price = 1000000000 }
